### ISSUE TITLE
Error: "Could not find package.json"

### ISSUE THREAD

**Issue by davidkpiano** [carloslfu/markdown-it-codesandbox-embed#1]
Getting this error while trying to build XState docs: 

```
(undefined) ./docs/examples/todomvc.md
Module build failed (from ./node_modules/vuepress/lib/webpack/markdownLoader.js):
Error: Server responded to https://codesandbox.io/api/v1/sandboxes/define?json=1 with status code 422:
{"errors":{"detail":["Could not find package.json"]}}
    at Response.getBody (/Users/davidkpiano/Code/xstate/node_modules/http-response-object/lib/index.js:41:23)
    at getSandboxURL (/Users/davidkpiano/Code/xstate/node_modules/markdown-it-codesandbox-embed/index.js:22:6)
    at Object.tokenizeReturn [as codesandbox] (/Users/davidkpiano/Code/xstate/node_modules/markdown-it-codesandbox-embed/index.js:85:24)
    at Renderer.renderInline (/Users/davidkpiano/Code/xstate/node_modules/markdown-it/lib/renderer.js:271:28)
    at Renderer.render (/Users/davidkpiano/Code/xstate/node_modules/markdown-it/lib/renderer.js:324:22)
    at MarkdownIt.render (/Users/davidkpiano/Code/xstate/node_modules/markdown-it/lib/index.js:543:24)
    at MarkdownIt.md.render.args [as render] (/Users/davidkpiano/Code/xstate/node_modules/vuepress/lib/markdown/index.js:72:25)
    at Object.module.exports (/Users/davidkpiano/Code/xstate/node_modules/vuepress/lib/webpack/markdownLoader.js:56:58)
 @ ./node_modules/vuepress/lib/app/.temp/routes.js 26:4-69
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/clientEntry.js
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js
```

I'll have to revert it for now, do you know what's going on here?

**Comment by carloslfu** [comment]
Hi @davidkpiano. Yes, each sandbox should have a `package.json` file like [here](https://github.com/davidkpiano/xstate/blob/e11a7735032b1711b354c2f2757d5e3c3e4fff0e/docs/sandboxes/todomvc/package.json) and the link name should match the directory name e.g. in `@[codesandbox](todomvc)`, there should be a `todomvc/` folder with a `package.json` file in the sandboxes folder. I'm using VuePress `v0.14.8`, can you give me more details to test what's happening?
